export const IDS: Record<string, Record<string, string>> = {
	MAIN: {
		LIST: 'main-chats-list',
		SEARCH: 'main-search-form',
		MESSAGE: 'main-message-form',
	},
	PROFILE: {
		ACD: 'profile-change-data',
		ACP: 'profile-change-password',
		ALG: 'profile-logout',
		ABS: 'profile-buttons',
		ASD: 'profile-save-data',
		ASP: 'profile-save-password',
		ACL: 'profile-cancel',
		FAC: 'profile-form',
	},
	AUTHORIZATION: {
		FORM: 'authorization-form',
		SUBMIT: 'authorization-submit',
		SIGNUP: 'authorization-signup',
		LOGIN_FIELD: 'authorization-login-field',
		LOGIN_INPUT: 'authorization-login-input',
		PSW_FIELD: 'authorization-psw-field',
		PSW_INPUT: 'authorization-psw-input',
	},
	REGISTRATION: {
		FORM: 'registration-form',
		SUBMIT: 'registration-submit',
		SIGNIN: 'registration-signin',
		EMAIL_FIELD: 'registration-email-field',
		EMAIL_INPUT: 'registration-email-input',
		LOGIN_FIELD: 'registration-login-field',
		LOGIN_INPUT: 'registration-login-input',
		F_NAME_FIELD: 'registration-first-name-field',
		F_NAME_INPUT: 'registration-first-name-input',
		S_NAME_FIELD: 'registration-second-name-field',
		S_NAME_INPUT: 'registration-second-name-input',
		PHONE_FIELD: 'registration-phone-field',
		PHONE_INPUT: 'registration-phone-input',
		PSW_FIELD: 'registration-psw-field',
		PSW_INPUT: 'registration-psw-input',
		C_PSW_FIELD: 'registration-c-psw-field',
		C_PSW_INPUT: 'registration-c-psw-input',
	},
	ERROR: {
		RETURN: 'error-return',
	},
	MODAL: {},
	COMMON: {
		INPUT: 'input',
	},
};
