export const IDS: Record<string, Record<string, string>> = {
	MAIN: {
		SEARCH_FORM: 'main-search-form',
		SEARCH_INPUT: 'main-search-input',
		CHAT_LIST: 'main-chat-list',
		MESSAGING: 'main-messaging',
		TEMP_NAV: 'main-dropdown-temp-nav',
	},
	PROFILE: {
		FORM: 'profile-form',
		AVATAR: 'profile-avatar',

		EMAIL_INPUT: 'profile-email-input',
		EMAIL_FIELD: 'profile-email-field',
		LOGIN_FIELD: 'profile-login-field',
		LOGIN_INPUT: 'profile-login-input',
		F_NAME_FIELD: 'profile-first-name-field',
		F_NAME_INPUT: 'profile-first-name-input',
		S_NAME_FIELD: 'profile-second-name-field',
		S_NAME_INPUT: 'profile-second-name-input',
		D_NAME_FIELD: 'profile-display-name-field',
		D_NAME_INPUT: 'profile-display-name-input',
		PHONE_FIELD: 'profile-phone-field',
		PHONE_INPUT: 'profile-phone-input',

		O_PSW_INPUT: 'profile-old-password-input',
		O_PSW_FIELD: 'profile-old-password-field',
		N_PSW_INPUT: 'profile-new-password-input',
		N_PSW_FIELD: 'profile-new-password-field',
		C_PSW_INPUT: 'profile-confirm-password-input',
		C_PSW_FIELD: 'profile-confirm-password-field',

		ASIDE_BTN: 'profile-aside-button',
		CHANGE_DATA_BTN: 'profile-change-data-button',
		CHANGE_PSW_BTN: 'profile-change-psw-button',
		LOGOUT_BTN: 'profile-logout-button',
		SAVE_PSW_BTN: 'profile-save-password-button',
		SAVE_DATA_BTN: 'profile-save-data-button',
		CANCEL_PSW_EDIT_BTN: 'profile-cancel-psw-edit-button',
		CANCEL_DATA_EDIT_BTN: 'profile-cancel-data-edit-button',
	},
	AUTHORIZATION: {
		FORM: 'authorization-form',
		SUBMIT: 'authorization-submit',
		SIGNUP: 'authorization-signup',
		LOGIN_FIELD: 'authorization-login-field',
		LOGIN_INPUT: 'authorization-login-input',
		PSW_FIELD: 'authorization-psw-field',
		PSW_INPUT: 'authorization-psw-input',

		// Временные кнопки для перехода на другие страницы
		TEMP_ERROR: 'authorization-temp-error',
		TEMP_PROFILE: 'authorization-temp-profile',
		TEMP_MAIN: 'authorization-temp-main',
		TEMP_MODAL: 'authorization-temp-modal',
	},
	REGISTRATION: {
		FORM: 'registration-form',
		SUBMIT: 'registration-submit',
		SIGNIN: 'registration-signin',
		EMAIL_FIELD: 'registration-email-field',
		EMAIL_INPUT: 'registration-email-input',
		LOGIN_FIELD: 'registration-login-field',
		LOGIN_INPUT: 'registration-login-input',
		F_NAME_FIELD: 'registration-first-name-field',
		F_NAME_INPUT: 'registration-first-name-input',
		S_NAME_FIELD: 'registration-second-name-field',
		S_NAME_INPUT: 'registration-second-name-input',
		PHONE_FIELD: 'registration-phone-field',
		PHONE_INPUT: 'registration-phone-input',
		PSW_FIELD: 'registration-psw-field',
		PSW_INPUT: 'registration-psw-input',
		C_PSW_FIELD: 'registration-c-psw-field',
		C_PSW_INPUT: 'registration-c-psw-input',
	},
	ERROR: {
		RETURN: 'error-return',
		BUTTON: 'error-button',
	},
	MODAL: {
		CONTENT: 'modal-content',
		SUBMIT: 'modal-submit',
		CLOSE: 'modal-close',
		ADD_USER_FIELD: 'modal-add-user-field',
		ADD_USER_INPUT: 'modal-add-user-input',
	},
	COMMON: {
		INPUT: 'input',
		COMPONENTS_LIST: 'components-list',
	},
	FORMS: {
		AUTHORIZATION_FORM: 'authorizationForm',
		REGISTRATION_FORM: 'registrationForm',
		PROFILE_USER_DATA_FORM: 'userForm',
		PROFILE_USER_PSW_FORM: 'passwordForm',
		MODAL_ADD_USER_FORM: 'modalAddUserForm',
		MAIN_CHAT_SEARCH_FORM: 'chatsSearchForm',
	},
};
