export const IDS: Record<string, Record<string, string>> = {
	MAIN: {
		LIST: 'main-chats-list',
		SEARCH: 'main-search-form',
		MESSAGE: 'main-message-form',
	},
	PROFILE: {
		FORM: 'profile-form',
		AVATAR: 'profile-avatar',
		EMAIL_INPUT: 'profile-email-input',
		EMAIL_FIELD: 'profile-email-field',
		O_PSW_INPUT: 'profile-old-password-input',
		O_PSW_FIELD: 'profile-old-password-field',
		ASIDE_BTN: 'profile-aside-button',
		CHANGE_DATA_BTN: 'profile-change-data-button',
		CHANGE_PSW_BTN: 'profile-change-psw-button',
		LOGOUT_BTN: 'profile-logout-button',
	},
	AUTHORIZATION: {
		FORM: 'authorization-form',
		SUBMIT: 'authorization-submit',
		SIGNUP: 'authorization-signup',
		LOGIN_FIELD: 'authorization-login-field',
		LOGIN_INPUT: 'authorization-login-input',
		PSW_FIELD: 'authorization-psw-field',
		PSW_INPUT: 'authorization-psw-input',

		// Временные кнопки для перехода на другие страницы
		TEMP_ERROR: 'authorization-temp-error',
		TEMP_PROFILE: 'authorization-temp-profile',
		TEMP_MAIN: 'authorization-temp-main',
	},
	REGISTRATION: {
		FORM: 'registration-form',
		SUBMIT: 'registration-submit',
		SIGNIN: 'registration-signin',
		EMAIL_FIELD: 'registration-email-field',
		EMAIL_INPUT: 'registration-email-input',
		LOGIN_FIELD: 'registration-login-field',
		LOGIN_INPUT: 'registration-login-input',
		F_NAME_FIELD: 'registration-first-name-field',
		F_NAME_INPUT: 'registration-first-name-input',
		S_NAME_FIELD: 'registration-second-name-field',
		S_NAME_INPUT: 'registration-second-name-input',
		PHONE_FIELD: 'registration-phone-field',
		PHONE_INPUT: 'registration-phone-input',
		PSW_FIELD: 'registration-psw-field',
		PSW_INPUT: 'registration-psw-input',
		C_PSW_FIELD: 'registration-c-psw-field',
		C_PSW_INPUT: 'registration-c-psw-input',
	},
	ERROR: {
		RETURN: 'error-return',
		BUTTON: 'error-button',
	},
	MODAL: {},
	COMMON: {
		INPUT: 'input',
	},
	FORMS: {
		AUTHORIZATION_FORM: 'authorizationForm',
		REGISTRATION_FORM: 'registrationForm',
		PROFILE_USER_DATA_FORM: 'userForm',
		PROFILE_USER_PSW_FORM: 'passwordForm',
	},
};
