export type { TPages } from './pages';
export type {
    IState,
    IFormState,
    ILoginForm,
    IRegistrationFormUi,
    TFormsFields,
    IPageState,
    IMainPageState,
    IChat,
    IUserBase,
    IChatLastMessage,
    TUserRole,
    IChatUserResponse,
    IErrorPageState,
    IProfilePageState,
    ISearchForm,
    IUserPasswordForm,
    IUserDataForm,
    IUserResponse,
    IMainPageHbsState,
    IProfilePageHbsState,
    IAddUserModalState,
    TModalFields,
    IModalState,
} from './state';
